---
title: "BISST0663_Final_Project"
author: "Jueshen Hou  Zimeng Ren"
date: "2024-10-09"
output: pdf_document
---


```{r install package in case you do not have it, eval=FALSE, include=FALSE}
##These packages are needed for later code chunks,if you do not have the following packages installed, please run this chunk to ensure all packages needed are installed.
install.packages(c("ggplot2","broom","gridExtra","dplyr","class","tidyverse","leaps","corrplot","RColorBrewer","glmnet","xtable","randomForest","pROC","devtools","UpSetR","naniar","report","rpart","rattle","rpart.plot"))
```

```{r load packages, include=FALSE}
##Here we load the packages needed and install a package that is not on CRAN
library(ggplot2)
library(broom)
library(gridExtra)
library(dplyr)
library(class)
library(tidyverse)
library(gridExtra)
library(leaps)
library(corrplot)
library(RColorBrewer)
library(glmnet)
library(xtable)
library(randomForest)
library(pROC)
#library(smotefamily)
library(devtools)
devtools::install_github("dongyuanwu/RSBID")
library(UpSetR)
library(naniar)
library(report)
library(rpart)
library(rattle)
library(rpart.plot)
library(DataExplorer)
```

### Load Data
```{r}
ALZH<-read.csv("C:/Users/24597/Documents/RUstatsLearning/alzheimers_disease_data.csv")
```

### Take a Look

```{r}
glimpse(ALZH)
```
```{r}
ALZH_noID<-ALZH[,-1]
```

```{r}
colSums(is.na(ALZH_noID))
```

```{r changing data types}
ALZH_noID$Diagnosis<-as.factor(ALZH_noID$Diagnosis)
ALZH_noID <- ALZH_noID %>%
  mutate(across(c(Gender, Ethnicity,EducationLevel,Smoking,FamilyHistoryAlzheimers,CardiovascularDisease,Diabetes,Depression,HeadInjury,Hypertension,MemoryComplaints,BehavioralProblems,Confusion,Disorientation,PersonalityChanges,DifficultyCompletingTasks,Forgetfulness), as.factor))
```


```{r}
glimpse(ALZH_noID)
```

```{r}
ALZH_IntOnly<-ALZH_noID[,sapply(ALZH_noID,is.integer)]
ALZH_double<-ALZH_noID[,sapply(ALZH_noID,is.double)]
ALZH_NumOnly<-cbind(ALZH_IntOnly,ALZH_double)
ALZH_fct<-ALZH_noID[,sapply(ALZH_noID,is.factor)]

```

```{r}
glimpse(ALZH_NumOnly)
```

```{r}
plot_qq(ALZH_NumOnly)
```



```{r}
glimpse(ALZH_noID)
```

```{r}
alzh_classes<-ggplot(data = ALZH_noID, mapping = aes(x=Diagnosis,fill=Diagnosis))+
  geom_bar()+
  xlab("Diagnosis Status")+
  ggtitle("Figure x.x Classes of Alzheimer's Disease")
  
alzh_classes
```

```{r}
plot_intro(ALZH_noID)
```

```{r}
plot_qq(ALZH_noID)
```

```{r}
plot_bar(ALZH_fct)
```


### KNN

### Boosting